---
{{ if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-kube.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-kube.labels" . | nindent 4 }}
# ..............................................................................
{{- with .Values.configMap.data }}
data:
{{ toYaml . | nindent 2 }}
{{- end }}
{{- end }}
