---
{{ if .Values.serviceAccount.create -}}
# Enable access rights for Checkmk for monitoring the Kubernetes cluster via the API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helm-kube.serviceAccountName" . }}
  labels:
    {{- include "helm-kube.labels" . | nindent 4 }}
# ..............................................................................
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken | default false }}
# ------------------------------------------------------------------------------
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm-kube.fullname" . }}
  labels:
    {{- include "helm-kube.labels" . | nindent 4 }}
# ..............................................................................
rules:
  {{- range $clusterRole := .Values.serviceAccount.clusterRole }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
# ------------------------------------------------------------------------------
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm-kube.fullname" . }}
  labels:
    {{- include "helm-kube.labels" . | nindent 4 }}
# ..............................................................................
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "helm-kube.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "helm-kube.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
