---
{{ if .Values.secretCredential.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-kube.fullname" . }}-credential
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-kube.labels" . | nindent 4 }}
# ..............................................................................
type: {{ .Values.secretCredential.type | default "Opaque" | quote }}

{{- with .Values.secretCredential.data }}
data:
{{ toYaml . | nindent 2 }}
{{- end }}
{{- end }}
# ------------------------------------------------------------------------------
---
{{ if .Values.secretToken.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-kube.fullname" . }}-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-kube.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.secretToken.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
# ..............................................................................
type: {{ .Values.secretToken.type | default "Opaque" | quote }}
{{- end }}
