apiVersion: v1
kind: Secret
metadata:
  name: checkmk
  namespace: checkmk-n
data:
  # Sets cmk as default password.
  # To set your own password, replace it, e.g.
  # using "echo -n 'password' | base64"
  password: c3dvcmRmaXNo
