---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkmk # name of the deployment
  namespace: checkmk-n # name of the namespace
  labels:
    app: checkmk # name of your application
# .......................................
spec:
  replicas: 2 # Number of replicas
  selector:
    matchLabels:
      app: checkmk # name of your application
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: checkmk # name of your application
    spec:
      serviceAccountName: checkmk-account
      securityContext: {}
      containers:
        - name: checkmk # name of the container
          image: checkmk/check-mk-free:2.1.0p11 # the image you want to run
          # image: checkmk/check-mk-raw:2.1.0p11 # the image you want to run
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 2Gi
              cpu: "2"
            requests:
              memory: 500Mi
              cpu: "1"
          env:
            - name: CMK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: checkmk-credential
                  key: password
            - name: CMK_SITE_ID
              valueFrom:
                configMapKeyRef:
                  name: checkmk
                  key: siteid
          ports:
            - name: http
              containerPort: 5000 # the port that your application uses
              protocol: TCP
            - name: api
              containerPort: 10050
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            timeoutSeconds: 2
            initialDelaySeconds: 15
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: tmpfs
              mountPath: /opt/omd/sites/cmk/tmp
            - name: data
              mountPath: /omd/sites
            - name: factor-token
              mountPath: /var/run/secrets/tokens
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: tmpfs
          emptyDir:
            medium: Memory
            sizeLimit: 64Mi
        - name: data
          persistentVolumeClaim:
            claimName: checkmk-data
        - name: factor-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: factors
                  expirationSeconds: 600
                  path: factor-token
