---
apiVersion: v1
kind: Service
metadata:
  name: checkmk
  namespace: monitoring
# .......................................
spec:
  selector:
    app: checkmk
  type: ClusterIP
  # ClusterIP means this service can be accessed by any pod in the cluster
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
