---
apiVersion: v1
kind: Service
metadata:
  name: checkmk
  namespace: checkmk-n
# .......................................
spec:
  selector:
    app: checkmk
  type: NodePort # ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
