---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-kube.fullname" . }}
  labels:
    {{- include "helm-kube.labels" . | nindent 4 }}
# ..............................................................................
data:
  config.yaml: |
    ...
