---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  annotations:
    # MODES:
    #   - enforce = any pods that violate the policy will be rejected
    #   - audit   = volations will be recorded as an annotation in the audit logs,
    #               but don' affect wheather the pod is allowed
    #   - warn    = violations will send a warning message back to the user,
    #               but don't affect wheater the pod is allwoed
    # LEVEL:
    #   - privileged = open and unrestricted
    #   - baseline   = covers know privilege escalations while minimizng restrictions
    #   - restricted = highy restrcited, hardening against know and unknown privilege escalations.
    #                  may cause compability issues
    # pod-security.kubernetes.io/<MODE>: <LEVEL>
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
