---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm-kube.fullname" . }}
  labels:
    {{- include "helm-kube.labels" . | nindent 4 }}
# ..............................................................................
spec:
  accessModes: ["ReadWriteOnce"]
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
